# Generated by Django 5.2.7 on 2025-12-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
